name: CI
on: [push, pull_request]

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile and run tests on robot code
      run: ./gradlew build
